//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/cliente/

###

POST http://localhost:3030/cliente/
Content-Type: application/json

{
    "documentoCliente": 2228882222,
    "idTipoDocumento": 1,
    "nombreCliente": "Jhon Freddy",
    "telefonoCliente": "3108323315",
    "correoCliente": "ooole@g.com",
    "direccionCliente": "Cra. 43a #110-23, La Isla, Medellín, Popular, Medellín, Antioquia, Colombia"
}

### Cuidado con la coma al final del json

PUT http://localhost:3030/cliente/54
Content-Type: application/json

{
    "idCliente": 54,
    "documentoCliente": 1000291725,
    "idTipoDocumento": 1,
    "nombreCliente": "Pablo",
    "telefonoCliente": "3108323315",
    "correoCliente": "holamundo@g.com",
    "direccionCliente": "Cra. 43a #110-23, La Isla, Medellín, Popular, Medellín, Antioquia, Colombia"
}

###

DELETE http://localhost:3030/cliente/9090