//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/estadoPaquete

###

POST http://localhost:3030/estadoPaquete
Content-Type: application/json

{
    "idEstado": 4,
    "estadoPaquete": "noEntregado"
}

###

PUT http://localhost:3030/estadoPaquete/20
Content-Type: application/json

{
    "estadoPaquete": "entregado"
}

###

DELETE http://localhost:3030/estadoPaquete/10