//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/listapaquete

###

POST http://localhost:3030/listaPaquete
Content-Type: application/json

{
    "idPaquete": 5
}

###

PUT http://localhost:3030/listaPaquete/13
Content-Type: application/json

{
    "idPaquete": "1"
}

###

DELETE http://localhost:3030/listaPaquete/12