//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/modulo

###

POST http://localhost:3030/modulo
Content-Type: application/json

{
    "modulo": "cliente"
}

###

PUT http://localhost:3030/modulo/13
Content-Type: application/json

{
    "modulo": "paquete"
}

###

DELETE http://localhost:3030/modulo/12