//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/novedad/

###

POST http://localhost:3030/novedad/
Content-Type: application/json

{
    "descripcionNovedad":"Me robaron",
    "idTipoNovedad":1,
    "idEntrega":2
}

###

DELETE http://localhost:3030/novedad/3