//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/paquete

###

POST http://localhost:3030/paquete/
Content-Type: application/json

{
    "codigoQrPaquete": "123",
    "pesoPaquete": 34.2,
    "documentoUsuario": 1023625668,
    "documentoRemitente": 1013337984,
    "documentoDestinatario": 23,
    "idEstado": 1,
    "idTamano": 1
}

### Cuidado con la coma al final del json

PUT http://localhost:3030/paquete/3
Content-Type: application/json

{
    "codigoQrPaquete": "29",
    "documentoUsuario":333,
    "documentoCliente":123,
    "idEstado": 20
}

###

DELETE http://localhost:3030/paquete/3