//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/rolPermiso

###

POST http://localhost:3030/permiso
Content-Type: application/json

{
    "fechaCreacion": "2021-05-05",
    
}

###

PUT http://localhost:3030/permiso/1
Content-Type: application/json

{
    "nombrePermiso": "utweye",
    "idModulo": "10"
}

###

DELETE http://localhost:3030/permiso/1