//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/tipoDocumentoUsuario

###

POST http://localhost:3030/tipoDocumentoUsuario
Content-Type: application/json

{
    "idTipoDocumento":4,
    "nombreTipo": "Tarjeta de identidad"
}

###

PUT http://localhost:3030/tipoDocumentoUsuario/2
Content-Type: application/json

{
    "nombreTipo": "Cedula de extranjería"
}

###

DELETE http://localhost:3030/tipoDocumentoUsuario/1