//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/usuarios/

###

POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "documentoUsuario":11,
    "idTipoDocumento":1,
    "nombreUsuario":"miltrus",
    "apellidoUsuario":"friedman",
    "telefonoUsuario":"3013784849",
    "correoUsuario":"miltrus@g.com",
    "contrasenaUsuario":"miltrus",
    "idRol":1,
    "idEstado":1
}

###

POST http://localhost:3030/login
Content-Type: application/json

{
    "correoUsuario":"coño",
    "contrasenaUsuario":"miltrusfriedman"
}

###

PUT http://localhost:3030/usuarios/11
Content-Type: application/json

{
    "documentoUsuario":11,
    "idTipoDocumento":4,
    "nombreUsuario":"miltrus",
    "apellidoUsuario":"friedman",
    "telefonoUsuario":"3013784849",
    "correoUsuario":"miltrus@g.com",
    "contrasenaUsuario":"miltrus",
    "idRol":1,
    "idEstado":1
}

###

DELETE http://localhost:3030/usuarios/1023625668