//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/cliente

###

POST http://localhost:3030/cliente/
Content-Type: application/json

{
    "documentoCliente":2222,
    "idTipoDocumento":1,
    "nombreCliente":"MiLTON",
    "telefonoCliente":"311111111",
    "correoCliente":"miltrus123@gmail.com",
    "direccionCliente":"KR11 #2-43"
}

### Cuidado con la coma al final del json

PUT http://localhost:3030/cliente/19
Content-Type: application/json

{
    "idTipoDocumento":1,
    "nombreCliente":"oqiowieowiweowie",
    "telefonoCliente":"311111111",
    "correoCliente":"awqa@pepe.co",
    "direccionCliente":"KR11 #2-43"
}

###

DELETE http://localhost:3030/cliente/222