//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/estadoUsuario

###

POST http://localhost:3030/estadoUsuario
Content-Type: application/json

{
    "idEstado":2,
    "estadoUsuario": "inactivo"
}

###

PUT http://localhost:3030/estadoUsuario/2
Content-Type: application/json

{
    "estadoUsuario": "jejje"
}

###

DELETE http://localhost:3030/estadoUsuario/1