//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/modulo

###

POST http://localhost:3030/modulo
Content-Type: application/json

{
    "modulo": "kjaks"
}

###

PUT http://localhost:3030/modulo/8
Content-Type: application/json

{
    "modulo": "holaaaa"
}

###

DELETE http://localhost:3030/modulo/8