//Este rest es para que reconzca este archivo como unarchivo de solicitudes

GET http://localhost:3030/roles

###

POST http://localhost:3030/roles
Content-Type: application/json

{
    "rol":"Empleado 2",
    "descripcion":"Nuevo integrante de la empresa"
}