//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/tipoDocumentoCliente

###

POST http://localhost:3030/tipoDocumentoCliente
Content-Type: application/json

{
    "nombreTipo": "pruebaa"
}

###

PUT http://localhost:3030/tipoDocumentoCliente/1
Content-Type: application/json

{
    "nombreTipo": "pruebaa"
}

###

DELETE http://localhost:3030/tipoDocumentoCliente/1