//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/tipoNovedad

###

POST http://localhost:3030/tipoNovedad
Content-Type: application/json

{
    "idTipoNovedad": 9,
    "tipoNovedad": "hola mijo"
}

###

PUT http://localhost:3030/tipoNovedad/4
Content-Type: application/json

{
    "idTipoNovedad": "4",
    "tipoNovedad": "auu"
}

###

DELETE http://localhost:3030/tipoNovedad/9