//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/tipoDocumentoUsuario

###

POST http://localhost:3030/tipoDocumentoUsuario
Content-Type: application/json

{
    "nombreTipo": "pruebaa"
}

###

PUT http://localhost:3030/tipoDocumentoUsuario/1
Content-Type: application/json

{
    "nombreTipo": "kjas"
}

###

DELETE http://localhost:3030/tipoDocumentoUsuario/1