//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/tipoNovedad

###

POST http://localhost:3030/tipoNovedad
Content-Type: application/json

{
    "idTipoNovedad": 1,
    "tipoNovedad": "Retraso"
}

###

PUT http://localhost:3030/tipoNovedad/1
Content-Type: application/json

{
    "idTipoNovedad": 3,
    "tipoNovedad": "wdsdsd"
}

###

DELETE http://localhost:3030/tipoNovedad/10