//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/usuarios/

###

POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "documentoUsuario":927398,
    "idTipoDocumento":4,
    "nombreUsuario":"roass",
    "apellidoUsuario":"ered",
    "telefonoUsuario":"333333333",
    "correoUsuario":"A@ererererer.co",
    "contrasenaUsuario":"Amolosaniomalestieamzoo",
    "idRol":2,
    "idEstado":1
}

###

PUT http://localhost:3030/usuarios/1023625668
Content-Type: application/json

{
    "documentoUsuario":23445767545458,
    "idTipoDocumento":12,
    "nombreUsuario":"Juan",
    "apellidoUsuario":"Chava",
    "telefonoUsuario":"3108323315",
    "correoUsuario":"carajoooo54545ooooo@papirico.co",
    "contrasenaUsuario":"Amolosaniomalestieamzoo",
    "idRol":1,
    "idEstado":1
}

###

DELETE http://localhost:3030/usuarios/6