//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/usuarios/1000291725

###

POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "documentoUsuario":3334,
    "idTipoDocumento":4,
    "nombreUsuario":"roass",
    "apellidoUsuario":"FEO2",
    "telefonoUsuario":"333333333",
    "correoUsuario":"A@pairico.co",
    "contrasenaUsuario":"Amolosaniomalestieamzoo",
    "idRol":1,
    "idEstado":1
}

###

PUT http://localhost:3030/usuarios/1
Content-Type: application/json

{
    "documentoUsuario":1000291725,
    "idTipoDocumento":1,
    "nombreUsuario":"Juan",
    "apellidoUsuario":"Chava",
    "telefonoUsuario":"3108323315",
    "correoUsuario":"pablosi14@papirico.co",
    "contrasenaUsuario":"Amolosaniomalestieamzoo",
    "idRol":1,
    "idEstado":1
}

###

DELETE http://localhost:3030/usuarios/6