//este rest es para que reconozca esete archivo como un archivo de solicitudes


GET http://localhost:3030/usuarios

###

POST http://localhost:3030/usuarios
Content-Type: application/json

{
    "id":1,
    "nombre": "los pepes",
    "email": "kwjk",
    "idRol": 1
}

###

PUT http://localhost:3030/usuarios/14
Content-Type: application/json

{
    "nombre": "Milton",
    "email": "ksjdowqkjoieowe",
    "idRol": 3
}

###

DELETE http://localhost:3030/usuarios/5